Add postgres and storage yaml
Jaxonwht/marketplace pull request #30
Opened 2022-07-22 05:20 UTC by zhoujc999

2022-07-22 05:21 UTC, zhoujc999 commented on k8s/postgres_deployment_prod.yaml
> +              value: web_prod
@Jaxonwht 改一下？

2022-07-22 05:21 UTC, zhoujc999 commented on k8s/postgres_deployment_prod.yaml
> +              value: web_prod
@Jaxonwht 改一下？

2022-07-22 14:12 UTC, Jaxonwht commented on k8s/postgres_deployment_prod.yaml
> +              value: web_prod
I thot we use expense db instead?

2022-07-23 05:35 UTC, Jaxonwht requested changes
Plan aborted

2022-07-24 00:39 UTC, closed without merging