Improve login flow (with bugs)
Jaxonwht/marketplace pull request #31
Opened 2022-07-23 00:47 UTC by zhoujc999

2022-07-23 05:35 UTC, Jaxonwht commented
With bugs? 什么几把

2022-07-24 00:30 UTC, Jaxonwht requested changes

2022-07-24 00:30 UTC, Jaxonwht commented on client/src/App.tsx
> +  });
empty array as dependency array here

2022-07-24 00:33 UTC, zhoujc999 commented on client/src/App.tsx
> +  });
@Jaxonwht https://github.com/Jaxonwht/marketplace/blob/f4fd09ee3371efdf7d635b38d6823767ae7efe93/client/src/App.tsx#L26 为啥这里不需要?

2022-07-24 00:38 UTC, Jaxonwht approved these changes

2022-07-24 00:38 UTC, merged