Add platform to user transaction
Jaxonwht/marketplace pull request #53
Opened 2022-08-03 08:03 UTC by zhoujc999

2022-08-04 00:45 UTC, Jaxonwht requested changes
可能我们需要pair program，这个你改不来

2022-08-04 00:45 UTC, Jaxonwht commented on web_backend/configs/base.py
> +    TRANSACTION_TYPE = "0x2"
DERFAQ is this

2022-08-04 00:45 UTC, Jaxonwht commented on web_backend/dal/deal_dal.py
> +            f"Issuing these shares require a balance of {dealer.lockup_balance + amount_needed}, but the dealer only has {dealer.balance}",
balacne 一下？

2022-08-04 00:45 UTC, Jaxonwht commented on web_backend/dal/platform_transaction_dal.py
> +    deducted_value: int = int(ceil(transfer_value * (1 + current_app.config["TRANSACTION_FEE_PERCENTAGE"])))
要不别int了 ded

2022-08-04 00:45 UTC, Jaxonwht commented on web_backend/dal/platform_transaction_dal.py
> +    deducted_value: int = int(ceil(transfer_value * (1 + current_app.config["TRANSACTION_FEE_PERCENTAGE"])))
不是

2022-08-04 00:45 UTC, Jaxonwht commented on web_backend/dal/platform_transaction_dal.py
> +            if dealer.balance < 0:
别这么写

2022-08-04 00:45 UTC, Jaxonwht commented on web_backend/dal/platform_transaction_dal.py
> +            if dealer.balance < 0:
dealer.balance < 0 会fail `CheckConstraint`. 应该在做update之前决定要不要minus 再minus A

2022-08-04 00:45 UTC, Jaxonwht commented on web_backend/dal/platform_transaction_dal.py
> +                    f"Withdrawing {transfer_value} require a balance of {deducted_value}, but the buyer only has {Buyer.balance}",
Same as above

2022-08-04 00:45 UTC, Jaxonwht commented on web_backend/dal/platform_transaction_dal.py
> +        "maxFeePerGas": w3.toWei("250", "gwei"),
加个TODO

2022-08-04 00:45 UTC, Jaxonwht commented on web_backend/dal/platform_transaction_dal.py
> +    transaction_hash = web3.eth.send_raw_transaction(signed_transaction.rawTransaction)
还需要把transaction_hash 加进 platform_transaction table A

2022-08-04 01:15 UTC, zhoujc999 commented on web_backend/dal/deal_dal.py
> +            f"Issuing these shares require a balance of {dealer.lockup_balance + amount_needed}, but the dealer only has {dealer.balance}",
强行resolve

2022-08-21 22:07 UTC, Jaxonwht approved these changes
LGTM

2022-08-21 22:08 UTC, merged